import type { SourceDefinition } from "./contracts.ts";

export const SOURCES: SourceDefinition[] = [
  {
    id: "openai-news",
    name: "OpenAI News",
    kind: "rss",
    feedUrl: "https://openai.com/news/rss.xml",
    homepageUrl: "https://openai.com/news/",
    region: "美国 / 全球",
    language: "en",
    authority: 100,
    official: true,
    snapshotAllowed: false,
    includeTerms: ["model", "research", "api", "safety", "agent"],
  },
  {
    id: "google-deepmind",
    name: "Google DeepMind",
    kind: "rss",
    feedUrl: "https://deepmind.google/blog/rss.xml",
    homepageUrl: "https://deepmind.google/discover/blog/",
    region: "英国 / 全球",
    language: "en",
    authority: 100,
    official: true,
    snapshotAllowed: false,
    includeTerms: ["model", "research", "science", "agent", "safety"],
  },
  {
    id: "aws-machine-learning",
    name: "AWS Machine Learning Blog",
    kind: "rss",
    feedUrl: "https://aws.amazon.com/blogs/machine-learning/feed/",
    homepageUrl: "https://aws.amazon.com/blogs/machine-learning/",
    region: "美国 / 全球",
    language: "en",
    authority: 92,
    official: true,
    snapshotAllowed: false,
    includeTerms: ["generative ai", "model", "agent", "bedrock", "inference"],
  },
  {
    id: "github-ai-ml",
    name: "GitHub AI & ML",
    kind: "rss",
    feedUrl: "https://github.blog/ai-and-ml/feed/",
    homepageUrl: "https://github.blog/ai-and-ml/",
    region: "全球",
    language: "en",
    authority: 92,
    official: true,
    snapshotAllowed: false,
    includeTerms: ["copilot", "agent", "model", "developer", "ai"],
  },
  {
    id: "github-changelog",
    name: "GitHub Changelog",
    kind: "rss",
    feedUrl: "https://github.blog/changelog/feed/",
    homepageUrl: "https://github.blog/changelog/",
    region: "全球",
    language: "en",
    authority: 94,
    official: true,
    snapshotAllowed: false,
    includeTerms: ["copilot", "models", "agent", "coding", "ai"],
  },
  {
    id: "cloudflare-blog",
    name: "Cloudflare Blog",
    kind: "rss",
    feedUrl: "https://blog.cloudflare.com/rss",
    homepageUrl: "https://blog.cloudflare.com/",
    region: "全球",
    language: "en",
    authority: 90,
    official: true,
    snapshotAllowed: false,
    includeTerms: ["workers ai", "agents", "vectorize", "model", "inference"],
  },
  {
    id: "arxiv-cs-ai",
    name: "arXiv cs.AI",
    kind: "atom",
    feedUrl:
      "https://export.arxiv.org/api/query?search_query=cat:cs.AI&sortBy=submittedDate&sortOrder=descending&max_results=50",
    homepageUrl: "https://arxiv.org/list/cs.AI/recent",
    region: "全球研究",
    language: "en",
    authority: 82,
    official: false,
    snapshotAllowed: true,
    includeTerms: [],
  },
  {
    id: "apple-machine-learning",
    name: "Apple Machine Learning Research",
    kind: "rss",
    feedUrl: "https://machinelearning.apple.com/rss.xml",
    homepageUrl: "https://machinelearning.apple.com/",
    region: "美国 / 全球",
    language: "en",
    authority: 96,
    official: true,
    snapshotAllowed: false,
    includeTerms: ["model", "research", "multimodal", "language", "vision"],
  },
  {
    id: "vercel-changelog",
    name: "Vercel Changelog",
    kind: "atom",
    feedUrl: "https://vercel.com/atom",
    homepageUrl: "https://vercel.com/changelog",
    region: "全球",
    language: "en",
    authority: 88,
    official: true,
    snapshotAllowed: false,
    includeTerms: ["ai", "model", "agent", "sdk", "inference"],
    maxResponseBytes: 4_000_000,
  },
  {
    id: "nist-news",
    name: "NIST News",
    kind: "rss",
    feedUrl: "https://www.nist.gov/news-events/news/rss.xml",
    homepageUrl: "https://www.nist.gov/artificial-intelligence",
    region: "美国 / 全球参考",
    language: "en",
    authority: 100,
    official: true,
    snapshotAllowed: false,
    includeTerms: ["artificial intelligence", "ai", "machine learning", "risk management"],
  },
];

export const SOURCE_HOST_ALLOWLIST = new Set(
  SOURCES.map((source) => new URL(source.feedUrl).hostname),
);

export function getSource(sourceId: string) {
  return SOURCES.find((source) => source.id === sourceId) ?? null;
}
