export type { IconProps } from "@phosphor-icons/react/ssr";

export {
  Pulse as Activity,
  ArrowLeft,
  ArrowUpRight,
  Bell,
  Bookmark,
  Robot as Bot,
  Check,
  Checks as CheckCheck,
  CheckCircle as CheckCircle2,
  CaretDown as ChevronDown,
  CaretRight as ChevronRight,
  DotOutline as CircleDot,
  Clock as Clock3,
  Command,
  Copy,
  Database,
  ArrowSquareOut as ExternalLink,
  Eye,
  Funnel as Filter,
  GithubLogo,
  GlobeHemisphereWest as Globe2,
  Tray as Inbox,
  Translate as Languages,
  Stack as Layers3,
  SquaresFour as LayoutDashboard,
  ListDashes as ListFilter,
  Envelope as Mail,
  List as Menu,
  DotsThree as MoreHorizontal,
  Newspaper,
  CrosshairSimple as Radar,
  Broadcast as Radio,
  ArrowClockwise as RefreshCw,
  Rss,
  MagnifyingGlass as Search,
  PaperPlaneTilt as Send,
  SlidersHorizontal as Settings2,
  ShareNetwork as Share2,
  ShieldCheck,
  SlidersHorizontal,
  Sparkle as Sparkles,
  Crosshair as Target,
  TrendUp as TrendingUp,
  X,
  Lightning as Zap,
} from "@phosphor-icons/react/ssr";
